/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CalculadoraController;

/**
 *
 * @author Ryan
 */
public class MainFrm extends javax.swing.JFrame {

    CalculadoraController controller = new CalculadoraController();
    
    /**
     * Creates new form MainFrm
     */
    public MainFrm() {
        initComponents();
        
        // Coloca o Form no centro da tela e tira o redimencionamento
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Calculadora");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Zero = new javax.swing.JButton();
        btn_Um = new javax.swing.JButton();
        btn_Dois = new javax.swing.JButton();
        btn_Tres = new javax.swing.JButton();
        btn_Seis = new javax.swing.JButton();
        btn_Cinco = new javax.swing.JButton();
        btn_Quatro = new javax.swing.JButton();
        btn_Nove = new javax.swing.JButton();
        btn_Oito = new javax.swing.JButton();
        btn_Sete = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        btn_CE = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Divisao = new javax.swing.JButton();
        btn_Subtracao = new javax.swing.JButton();
        btn_Multiplicacao = new javax.swing.JButton();
        btn_Igual = new javax.swing.JButton();
        btn_Soma = new javax.swing.JButton();
        pnl_PreviewConta = new javax.swing.JPanel();
        txt_Conta = new javax.swing.JTextField();
        lbl_OperacaoAnterior = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Zero.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Zero.setText("0");
        btn_Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ZeroActionPerformed(evt);
            }
        });

        btn_Um.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Um.setText("1");
        btn_Um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UmActionPerformed(evt);
            }
        });

        btn_Dois.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Dois.setText("2");
        btn_Dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoisActionPerformed(evt);
            }
        });

        btn_Tres.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Tres.setText("3");
        btn_Tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TresActionPerformed(evt);
            }
        });

        btn_Seis.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Seis.setText("6");
        btn_Seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeisActionPerformed(evt);
            }
        });

        btn_Cinco.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Cinco.setText("5");
        btn_Cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CincoActionPerformed(evt);
            }
        });

        btn_Quatro.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Quatro.setText("4");
        btn_Quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuatroActionPerformed(evt);
            }
        });

        btn_Nove.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Nove.setText("9");
        btn_Nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NoveActionPerformed(evt);
            }
        });

        btn_Oito.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Oito.setText("8");
        btn_Oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OitoActionPerformed(evt);
            }
        });

        btn_Sete.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Sete.setText("7");
        btn_Sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeteActionPerformed(evt);
            }
        });

        btn_C.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_C.setText(",");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });

        btn_CE.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_CE.setText(".");
        btn_CE.setEnabled(false);

        btn_Delete.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Delete.setText("De");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Divisao.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Divisao.setText("/");
        btn_Divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DivisaoActionPerformed(evt);
            }
        });

        btn_Subtracao.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Subtracao.setText("-");
        btn_Subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubtracaoActionPerformed(evt);
            }
        });

        btn_Multiplicacao.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Multiplicacao.setText("x");
        btn_Multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultiplicacaoActionPerformed(evt);
            }
        });

        btn_Igual.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Igual.setText("=");

        btn_Soma.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_Soma.setText("+");
        btn_Soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SomaActionPerformed(evt);
            }
        });

        txt_Conta.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txt_Conta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ContaKeyTyped(evt);
            }
        });

        lbl_OperacaoAnterior.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbl_OperacaoAnterior.setText("...");

        javax.swing.GroupLayout pnl_PreviewContaLayout = new javax.swing.GroupLayout(pnl_PreviewConta);
        pnl_PreviewConta.setLayout(pnl_PreviewContaLayout);
        pnl_PreviewContaLayout.setHorizontalGroup(
            pnl_PreviewContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PreviewContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_PreviewContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Conta)
                    .addComponent(lbl_OperacaoAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_PreviewContaLayout.setVerticalGroup(
            pnl_PreviewContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PreviewContaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lbl_OperacaoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Conta)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Um, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Dois, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Sete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Oito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Nove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_PreviewConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_PreviewConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Sete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Oito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Nove, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Um, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Dois, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ContaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ContaKeyTyped
        
        // Rotina para filtras apenas os caracteres que eu preciso para realizar os calculos
        String chars = "0123456789+-*/,";
        
        if(!chars.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
        else {
            controller.EscrevePreview(String.valueOf(evt.getKeyChar()), txt_Conta);
            evt.consume();
        }
    }//GEN-LAST:event_txt_ContaKeyTyped

    private void btn_ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ZeroActionPerformed
        controller.EscrevePreview("0", txt_Conta);
    }//GEN-LAST:event_btn_ZeroActionPerformed

    private void btn_UmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UmActionPerformed
        controller.EscrevePreview("1", txt_Conta);
    }//GEN-LAST:event_btn_UmActionPerformed

    private void btn_DoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoisActionPerformed
        controller.EscrevePreview("2", txt_Conta);
    }//GEN-LAST:event_btn_DoisActionPerformed

    private void btn_TresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TresActionPerformed
        controller.EscrevePreview("3", txt_Conta);
    }//GEN-LAST:event_btn_TresActionPerformed

    private void btn_QuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuatroActionPerformed
        controller.EscrevePreview("4", txt_Conta);
    }//GEN-LAST:event_btn_QuatroActionPerformed

    private void btn_CincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CincoActionPerformed
        controller.EscrevePreview("5", txt_Conta);
    }//GEN-LAST:event_btn_CincoActionPerformed

    private void btn_SeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeisActionPerformed
        controller.EscrevePreview("6", txt_Conta);
    }//GEN-LAST:event_btn_SeisActionPerformed

    private void btn_SeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeteActionPerformed
        controller.EscrevePreview("7", txt_Conta);
    }//GEN-LAST:event_btn_SeteActionPerformed

    private void btn_OitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OitoActionPerformed
        controller.EscrevePreview("8", txt_Conta);
    }//GEN-LAST:event_btn_OitoActionPerformed

    private void btn_NoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NoveActionPerformed
        controller.EscrevePreview("9", txt_Conta);
    }//GEN-LAST:event_btn_NoveActionPerformed

    private void btn_SomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SomaActionPerformed
        controller.EscrevePreview("+", txt_Conta);
    }//GEN-LAST:event_btn_SomaActionPerformed

    private void btn_SubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubtracaoActionPerformed
        controller.EscrevePreview("-", txt_Conta);
    }//GEN-LAST:event_btn_SubtracaoActionPerformed

    private void btn_MultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultiplicacaoActionPerformed
        controller.EscrevePreview("*", txt_Conta);
    }//GEN-LAST:event_btn_MultiplicacaoActionPerformed

    private void btn_DivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DivisaoActionPerformed
        controller.EscrevePreview("/", txt_Conta);
    }//GEN-LAST:event_btn_DivisaoActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        txt_Conta.setText("");
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        controller.EscrevePreview(",", txt_Conta);
    }//GEN-LAST:event_btn_CActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_CE;
    private javax.swing.JButton btn_Cinco;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Divisao;
    private javax.swing.JButton btn_Dois;
    private javax.swing.JButton btn_Igual;
    private javax.swing.JButton btn_Multiplicacao;
    private javax.swing.JButton btn_Nove;
    private javax.swing.JButton btn_Oito;
    private javax.swing.JButton btn_Quatro;
    private javax.swing.JButton btn_Seis;
    private javax.swing.JButton btn_Sete;
    private javax.swing.JButton btn_Soma;
    private javax.swing.JButton btn_Subtracao;
    private javax.swing.JButton btn_Tres;
    private javax.swing.JButton btn_Um;
    private javax.swing.JButton btn_Zero;
    private javax.swing.JLabel lbl_OperacaoAnterior;
    private javax.swing.JPanel pnl_PreviewConta;
    private javax.swing.JTextField txt_Conta;
    // End of variables declaration//GEN-END:variables
}
